### PR TITLE
Bulk python3 print port

### PR DESCRIPTION
**Pull request by noelpower**
Another large low hanging fruit patch to try and address the many many print statements when can't run in python3. Again roughly divided into patches as was done previously

### CODE REVIEW

**Comment by abartlet** [comment]
You broke autobuild.py which is why this failed travis-ci.

**Comment by frenzymadness** [comment]
Hello.

I did a quick review and I have just two nitpicks:
* It would be nice to unify all empty prints to `print("")` but more preferably to  `print()`.
* It would be also nice to fix indentation in places where `file=sys.stderr` is moved at the end of lines. For example: https://github.com/samba-team/samba/pull/146/files#diff-c9a916b89694bec111daf93eb63b8b47R196

Consider my notes as just ideas becuae they have no impact to actual functionality.

Now it seems that CI is passing so we might be ready for a merge.

Thanks a lot!

**Comment by catalyst-joe-guo** [comment]
Andrew already merged this one, it can be closed now.

**Comment by abartlet** [comment]
Closing this one, please file a new PR with the requested fixes.

Merged to master for Samba 4.9 as 0844c5aa22c60404044b4e6dfa51ec301194cb2a

**Comment by abartlet** [comment]
As mentioned elsewhere, the patch for Heimdal needs to go via Heimdal first, if at possible.

**Pull request closed without merging**
