### PR TITLE
Fix little typo in README file

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by abartlet** [comment]
Sadly one of the downsides of the way that the Samba Team uses github is that you can't directly merge.  You need to go via autobuild.

This merge will be undone as soon as I disable to force-push protection and the mirror script runs again.

**Comment by GuillaumeGomez** [comment]
Well, whatever. I won't report the change myself, so I guess someone from the samba team (or someone else) will have to do it. At least, now you know it exists.

**Comment by abartlet** [comment]
@GuillaumeGomez I'm sorry I wasn't clear, this isn't your issue.  My comment was to @bjacke who is on the Samba Team, and so can get the code reviewed and submitted via the normal methods.

We realise this is very confusing (and contrary to standard github workflow), but we will get your change in shortly. 

Thanks!

**Comment by GuillaumeGomez** [comment]
Oh my bad. Well, like I said, the goal was to fix the typo, so as long as it's fixed at the end, it's fine for me.

**Comment by abartlet** [comment]
Merged as 2a55a0b370affaef0455320ddfd78bae4e413743

**Pull request merged**
