### PR TITLE
Readme GitHub

### PR DESCRIPTION
**Pull request by Gazzonyx**
Added some GitHub notes to the contribution section of the README.

### CODE REVIEW

**Comment by Gazzonyx** [comment]
Pushed Rev2 to the README-github branch.  
_Let's see if this comment makes the samba-technical list but the addition of the pushed commit doesn't._

**Comment by abartlet** [comment]
Can you rebase this into a single patch?

Thanks,

Andrew Bartlett

**Comment by Gazzonyx** [comment]
D'oh!  I forgot about this.  I'll rebase and push it to this PR.

**Comment by abartlet** [comment]
Merged as 843cb8ec5b92ef72421952d5503c1deec1559fe8

**Pull request closed without merging**
