### PR TITLE
CTDB: Use socket_wrapper only with selftest

### PR DESCRIPTION
**Pull request by sathieu**

### CODE REVIEW

**Comment by sathieu** [comment]
Same as c0a463d94abb5c50eaca7b1d402c979684f96a97

**Comment by gladiac** [comment]
Please add your Signed-off: to the patch ...

**Comment by obnoxxx** [comment]
The patch itself looks good to me, but it seems a rebase is needed with conflict resolution.

**Comment by amitay** [comment]
This patch has already been pushed.

**Comment by obnoxxx** [comment]
ok ... communication on too many sides ... :-)

**Pull request closed without merging**
