### PR TITLE
Samba on waf 19

### PR DESCRIPTION
**Pull request by ita1024**

### CODE REVIEW

**Comment by ita1024** [comment]
These changes enable building Samba using Waf 1.8.

Since the build would then require Python 2.7 - 3.X for building (or the actual waf file for building with Python 2.5-2.6), I am not sure that the changes would get merged soon. This is yet one thing to consider.

**Comment by ita1024** [comment]
Good to know. There is some more work to fix the tests but the local build seems to work at least.

**Comment by metze-samba** [comment]
I'm getting this:

./configure.developer  --fatal-errors --picky-developer --git-local-changes --enable-fhs --prefix=/home/metze/devel/prefix/samba3-waf/usr --sysconfdir=/home/metze/devel/prefix/samba3-waf/etc --localstatedir=/home/metze/devel/prefix/samba3-waf/var --with-selftest-prefix=/data/tmp/samba-masterF --with-cluster-support --with-pam --with-acl-support --with-profiling-data --extra-python=/usr/bin/python3 
Setting top to                           : /home/metze/devel/samba/3.X/masterF 
Setting out to                           : /home/metze/devel/samba/3.X/masterF/bin 
Checking for 'gcc' (C compiler)          : Traceback (most recent call last):
  File "/home/metze/devel/samba/3.X/masterF/third_party/waf/waflib/Scripting.py", line 165, in waf_entry_point
    run_commands()
  File "/home/metze/devel/samba/3.X/masterF/third_party/waf/waflib/Scripting.py", line 267, in run_commands
    ctx = run_command(cmd_name)
  File "/home/metze/devel/samba/3.X/masterF/third_party/waf/waflib/Scripting.py", line 251, in run_command
    ctx.execute()
  File "/home/metze/devel/samba/3.X/masterF/third_party/waf/waflib/Configure.py", line 165, in execute
    super(ConfigurationContext, self).execute()
  File "/home/metze/devel/samba/3.X/masterF/third_party/waf/waflib/Context.py", line 226, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/metze/devel/samba/3.X/masterF/third_party/waf/waflib/Context.py", line 304, in recurse
    user_function(self)
  File "/home/metze/devel/samba/3.X/masterF/wscript", line 103, in configure
    conf.RECURSE('lib/replace')
  File "/home/metze/devel/samba/3.X/masterF/third_party/waf/waflib/Configure.py", line 339, in fun
    return f(*k, **kw)
  File "./buildtools/wafsamba/samba_utils.py", line 453, in RECURSE
    return ctx.recurse(relpath)
  File "/home/metze/devel/samba/3.X/masterF/third_party/waf/waflib/Context.py", line 304, in recurse
    user_function(self)
  File "/home/metze/devel/samba/3.X/masterF/third_party/waf/waflib/Utils.py", line 748, in wrap
    ret = fun(k)
  File "/home/metze/devel/samba/3.X/masterF/lib/replace/wscript", line 28, in configure
    conf.RECURSE('buildtools/wafsamba')
  File "/home/metze/devel/samba/3.X/masterF/third_party/waf/waflib/Configure.py", line 339, in fun
    return f(*k, **kw)
  File "./buildtools/wafsamba/samba_utils.py", line 453, in RECURSE
    return ctx.recurse(relpath)
  File "/home/metze/devel/samba/3.X/masterF/third_party/waf/waflib/Context.py", line 304, in recurse
    user_function(self)
  File "/home/metze/devel/samba/3.X/masterF/third_party/waf/waflib/Utils.py", line 748, in wrap
    ret = fun(k)
  File "/home/metze/devel/samba/3.X/masterF/buildtools/wafsamba/wscript", line 227, in configure
    conf.check_tool('compiler_cc')
  File "/home/metze/devel/samba/3.X/masterF/third_party/waf/waflib/Configure.py", line 270, in load
    if type(func) is type(Utils.readf): func(self)
  File "/home/metze/devel/samba/3.X/masterF/third_party/waf/waflib/Tools/compiler_c.py", line 75, in configure
    conf.load(compiler)
  File "/home/metze/devel/samba/3.X/masterF/third_party/waf/waflib/Configure.py", line 270, in load
    if type(func) is type(Utils.readf): func(self)
  File "/home/metze/devel/samba/3.X/masterF/third_party/waf/waflib/Tools/gcc.py", line 151, in configure
    conf.find_gcc()
  File "/home/metze/devel/samba/3.X/masterF/third_party/waf/waflib/Configure.py", line 339, in fun
    return f(*k, **kw)
  File "/home/metze/devel/samba/3.X/masterF/third_party/waf/waflib/Tools/gcc.py", line 20, in find_gcc
    conf.get_cc_version(cc, gcc=True)
  File "/home/metze/devel/samba/3.X/masterF/third_party/waf/waflib/Configure.py", line 339, in fun
    return f(*k, **kw)
  File "/home/metze/devel/samba/3.X/masterF/third_party/waf/waflib/Tools/c_config.py", line 1043, in get_cc_version
    cmd = cc + ['-dM', '-E', '-']
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'

**Comment by metze-samba** [comment]
Without CC="", I'm getting this:

...
Checking for program 'xsltproc'                                                   : /usr/bin/xsltproc 
Checking for program 'python'                                                     : /usr/bin/python3 
Checking for program 'python'                                                     : /usr/bin/python 
Checking for python version                                                       : (2, 7, 6, 'final', 0) 
extra-python needs to be Python 3.3 or later
The python version is too old, expecting (3, 3, 0)
(complete log in /home/metze/devel/samba/3.X/masterF/bin/config.log)

**Comment by ita1024** [comment]
@metze-samba The CC case is not handled at this point. The branch was updated yesterday evening, the Travis tests fail on something else https://travis-ci.org/samba-team/samba/jobs/220353837

**Comment by ita1024** [comment]
The python-config defines `NDEBUG` and `_FORTIFY_SOURCE=2` were ignored by waf 1.5, so a tweak is necessary to remove them in the new build. Is it correct to do so? A few new `-f` flags appeared as well.

**Comment by abartlet** [comment]
This is what I get on my box:

[abartlet@jesse samba-push]$ python-config --cflags
-I/usr/include/python2.7 -I/usr/include/python2.7 -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv
[abartlet@jesse samba-push]$ python-config --includes
-I/usr/include/python2.7 -I/usr/include/python2.7

I don't see any good reason why we want all the --cflags output.  Some of those options might be very interesting, but they shouldn't come to Samba via python.

**Comment by ita1024** [comment]
@abartlet Removing all of them seems to break the -O3 build https://travis-ci.org/samba-team/samba/jobs/222427493
I suggest removing only `_FORTIFY_SOURCE=2` and `NDEBUG` for the time being.

**Comment by ita1024** [comment]
I think this is it. The changes should be relatively easy to review.

The waf files in the third patch are from 1.9.10, automatically expanded to run on Python 2.6-2.7.

Please modify an apply them as you see it fit; I can provide more enhancements after that, but remember that I cannot support a parallel branch for the years to come :-)

**Comment by metze-samba** [comment]
Thanks! The build on my system works now with:
https://git.samba.org/?p=metze/samba/wip.git;a=shortlog;h=refs/heads/master3-waf1.9-tmp2

But a private autobuild failed on the samba-xc target with:
Fatal Python error: Couldn't create autoTLSkey mapping
Aborted (core dumped)

Is it intended that the build output is printed via stdout now,
it was on stderr before.

**Comment by metze-samba** [comment]
It seems that Fatal Python error: Couldn't create autoTLSkey mapping is triggered by using some ulimit resrictions or virtual memory.

Is it expected that more memory is required?

**Comment by metze-samba** [comment]
Without the ulimit I'm betting this in samba-systemkrb5.stdout:

Checking for 'gssapi'                                                                           : yes 
Traceback (most recent call last):
  File "/memdisk/metze/W/b225959/samba-systemkrb5/third_party/waf/waflib/Scripting.py", line 171, in waf_entry_point
    run_commands()
  File "/memdisk/metze/W/b225959/samba-systemkrb5/third_party/waf/waflib/Scripting.py", line 272, in run_commands
    ctx = run_command(cmd_name)
  File "/memdisk/metze/W/b225959/samba-systemkrb5/third_party/waf/waflib/Scripting.py", line 256, in run_command
    ctx.execute()
  File "/memdisk/metze/W/b225959/samba-systemkrb5/third_party/waf/waflib/Configure.py", line 163, in execute
    super(ConfigurationContext, self).execute()
  File "/memdisk/metze/W/b225959/samba-systemkrb5/third_party/waf/waflib/Context.py", line 209, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/memdisk/metze/W/b225959/samba-systemkrb5/third_party/waf/waflib/Context.py", line 291, in recurse
    user_function(self)
  File "/memdisk/metze/W/b225959/samba-systemkrb5/wscript", line 163, in configure
    conf.PROCESS_SEPARATE_RULE('system_mitkrb5')
  File "./buildtools/wafsamba/samba_waf18.py", line 141, in PROCESS_SEPARATE_RULE
    exec(compile(txt, script.abspath(), 'exec'), dc)
  File "/memdisk/metze/W/b225959/samba-systemkrb5/wscript_configure_system_mitkrb5", line 56, in <module>
    vendor = conf.cmd_and_log("%(path)s --vendor" % dict(path=conf.env.KRB5_CONFIG), dict())
TypeError: cmd_and_log() takes exactly 2 arguments (3 given)

**Comment by ita1024** [comment]
@metze-samba the changes worked back in April, now there are even file conflicts :-/

**Comment by ita1024** [comment]
You could try adding:
https://github.com/ita1024/samba/commit/b33c67728b56d5c6224983801fb544d66d66d554
https://github.com/ita1024/samba/commit/f520ffd4173d19a1d41bb11bc005032d16c17ca8

The stderr/stdout settings are intentional. For the other issues, i do not even remember how to run the test suite on all projects, but it is very likely that changes made in wscript files since April are causing regressions.

**Comment by abartlet** [comment]
An effort including this patch is ongoing on samba-technical at the moment. 

The branch is at https://github.com/dmulder/samba/tree/python3_ports

Closing this in favour of that effort.  Thanks!

**Pull request closed without merging**
