### PR TITLE
lib/param: handle (ignore) substitution variable in smb.conf

### PR DESCRIPTION
**Pull request by QGuLL**
Signed-off-by: Quentin Gibeaux <qgibeaux@iris-tech.fr>

Pull request of fix in regards to https://bugzilla.samba.org/show_bug.cgi?id=10722

Summary  (see bugtrack for details) : 
I've encountered an annoying bug with samba-tool, some exceptions aren't caught causing the tool to crash if it finds something it doesn't like in the smb.conf.
I have a specific line in my conf : "include = /etc/samba/%U.smb.conf ", it's useful for applying specific samba configuration for a specific user, it works on the samba side, but when samba-tool reads the conf, it crashs :

root@server:~/samba# samba-tool user list
Processing section "[global]"
(…)
Can't find include file /etc/samba/%U.smb.conf
params.c:pm_process() - Failed. Error returned from params.c:parse().
pm_process() returned No
ERROR(runtime): uncaught exception - Unable to load default file
File "/usr/lib/python2.7/dist-packages/samba/netcmd/__init__.py", line 175, in _run
return self.run(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/samba/netcmd/user.py", line 261, in run
lp = sambaopts.get_loadparm()
File "/usr/lib/python2.7/dist-packages/samba/getopt.py", line 92, in get_loadparm
self._lp.load_default()

In fact it crashes for any include with any variable substitution (%U, %g, %a…).

### CODE REVIEW

**Comment by rodo** [comment]
Thanks for this patch @QGuLL I have exactly the same problem and do monkey patch each time a new version is released and deployed on our infra.
Hope to see it merge soon, as I see on https://bugzilla.samba.org/show_bug.cgi?id=10722 there is no technical issues to see it in next release, or in next hotfix.

**Comment by obnoxxx** [comment]
Generally, the patch looks good, as previously discussed. (Sorry for the delay...)

But a few (cosmetic comments regarding the patch):

* The else branch is not necessary, due to the return.
  ==> Please reduce indentation by removing the else (and moving the variable def's up)

* Please use "if (substitution_variable_substring != NULL)" 
   instead of " if (substitution_variable_substring) "

* Please explain a bit more about the problem your patch is solving in the commit message
  and include a line
  "BUG: https://bugzilla.samba.org/show_bug.cgi?id=10722"

With these changes. I'll be good.

Thanks - Michael

**Comment by QGuLL** [comment]
I don't know how i did this but i initialy missed my git push (c98f1b3), but i've fixed it with 0d37c0c and 17a80fc.
I've fixed my patch with your advises, @obnoxxx .

**Comment by QGuLL** [comment]
The patch has been accepted from the bugtracker, i'm closing it
https://github.com/samba-team/samba/commit/3c6ea3293c6aac67bc442f47185fd494714e4806

**Comment by rodo** [comment]
Congrats @QGuLL

**Pull request closed without merging**
