### PR TITLE
Fix various spelling errors

### PR DESCRIPTION
**Pull request by sathieu**

### CODE REVIEW

**Comment by sathieu** [comment]
Those are mostly harmless (comments or error strings).

Still, carefully review the following:
* source3/include/MacExtensions.h : should the typo be kept?
* source4/heimdal/lib/asn1/rfc2459.asn1, even if the typo is not in the RFC

**Comment by sathieu** [comment]
Not done:
```
git grep GP_LINK_UNKOWN
grep -i ressource source3/modules/vfs_fruit.c
git grep ressource_id
```

**Comment by sathieu** [comment]
I removed third-party patches and rebased.

Thanks for your review.

**Comment by obnoxxx** [comment]
Thanks for the patch. Looks good to me.
Reviewed-by: me.

**Comment by abartlet** [comment]
Merged as c315fce17ef11a23c24fc92b7475ac3a3ac55032

**Pull request closed without merging**
